#!/bin/sh -x

#PORT=$(cat port)
PORT=5555

AUDIO_CAPS="application/x-rtp,media=(string)audio,clock-rate=(int)48000,encoding-name=(string)OPUS"

exec gst-launch-1.0 -vvv udpsrc address=:: port=$PORT ! 'application/x-rtp,payload=96,encoding-name=H264'! rtph264depay ! decodebin ! glimagesink \
#	udpsrc address=:: port=7777 ! "$AUDIO_CAPS" ! rtpopusdepay ! opusdec ! alsasink sync=no
