#!/bin/sh

. /etc/rc.subr

name="peervpn"
rcvar=peervpn_enable

command="/usr/sbin/daemon"
procname="peervpn"
peervpn_flags="-f -t $procname /usr/local/sbin/peervpn /usr/local/etc/peervpn-ewindow.conf"

start_precmd=peervpn_prestart

mac_addr()
{
  mac=$(ifconfig em0 | grep ether | cut -f 2 -d " ")
  echo -n $mac | sed 's/.//3;s/.//8;s/.//13;'
#  echo /64
}

#V6ADDR=fde1:c0fe::`sed 's/.//3;s/.//8;s/.//13;' /sys/class/net/eth0/address`/64


peervpn_prestart()
{
  echo prestart
  ifconfig tap0 create
  ifconfig tap0 10.7.7.7
  ifconfig tap0 inet6 fde1:c0fe::$(mac_addr)
#  route -6 add -net fde1:c0fe:: -interface tap0
}

load_rc_config $name
 : ${peervpn_enable:=no}

run_rc_command "$1"
