#!/bin/sh -x

cd "$(dirname $0)"

# To be called from /etc/service/ewindow/run Stuff to execute on boot by root user

modprobe bcm2835_v4l2

./service/peervpn/iproute2

# Prepare TAP device to run peervpn as user
#HOSTNAME=ewindow-$(cat /home/ewindow/config/id)
#hostname $HOSTNAME
#echo $HOSTNAME > /etc/hostname

V6ADDR=fde1:c0fe::`sed 's/.//3;s/.//8;s/.//13;' /sys/class/net/eth0/address`/64
echo "Ipv6 VPN Address: " $V6ADDR

# Disable screen blanking
sh -c "TERM=linux setterm -blank 0 >/dev/tty0"

exec su ewindow -s /bin/sh -c "svscan ./service"

