#!/bin/sh -ex

cd "$(dirname $0)"

# To be called from /etc/service/ewindow/run
# Stuff to execute on boot by root user

# Prepare TAP device to run peervpn as user
#ip tuntap add dev ewindow0 mode tap user ewindow
#ifconfig ewindow0 $(cat /home/ewindow/config/ip)/24
#HOSTNAME=ewindow-$(cat /home/ewindow/config/id)
#hostname $HOSTNAME
#echo $HOSTNAME > /etc/hostname

# Disable screen blanking
sudo sh -c "TERM=linux setterm -blank 0 >/dev/tty0"

sudo -u ewindow svscan ./service

