#!/bin/sh -ex

cd $(dirname $0)

HOST=$(cat host)
#PORT=$(cat port)
PORT=5555

exec gst-launch-1.0 -vvv autovideosrc ! "video/x-raw,width=640,height=480" ! omxh264enc target-bitrate=800000 control-rate=1  ! "video/x-h264,profile=high" ! h264parse ! rtph264pay pt=96 config-interval=1 !  udpsink host=$HOST port=$PORT \
#	alsasrc device=plughw:1 ! "audio/x-raw,channels=1,rate=48000" ! opusenc complexity=0 bandwidth=narrowband ! udpsink host=$HOST port=7777


# PC VERSION
#exec gst-launch-1.0 v4l2src ! "video/x-raw,width=640,height=480" ! x264enc ! rtph264pay ! udpsink host=localhost port=5555
